### ISSUE TITLE
code for grease pencil giving error

### ISSUE THREAD

**Issue by javismiles** [5agado/data-science-learning#1]
Good day,
Im following your excellent article and using the latest blender version

https://towardsdatascience.com/blender-2-8-grease-pencil-scripting-and-generative-art-cbbfd3967590

I get errors when trying to use your code, like here:
`gp_layer = init_grease_pencil()
gp_frame = gp_layer.frames.new(0)

draw_line(gp_frame, (0, 0, 0), (1, 1, 0))`

Traceback (most recent call last):
  File "C:\MEDIA\DL\LAND\losslandscapeCode\transformers\grease.blend\Text", line 64, in <module>
  File "C:\MEDIA\DL\LAND\losslandscapeCode\transformers\grease.blend\Text", line 47, in init_grease_pencil
  File "C:\MEDIA\DL\LAND\losslandscapeCode\transformers\grease.blend\Text", line 11, in get_grease_pencil
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "view_align" unrecognized
Error: Python script failed, check the message in the system console

any tips? thank you so much :)

**Comment by 5agado** [comment]
Could you be more specific on what are you running?
I don't see any reference to my code in the traceback, so unless something has been cut, it must be a Blender version/issue.

**Comment by 5agado** [comment]
Please rely on the [code present in this repo](https://github.com/5agado/data-science-learning/blob/47807109abb2416a71eb2a80099f92a7c7db2a2d/ds_utils/blender_utils.py#L194).

I assume the issue for the script you used is just the `view_align` argument, removing that should fix it.
